'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsProspectos"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsProspectos
    Inherits Global.System.Data.DataSet
    
    Private tablePROSPECTO_RECURSOS_LISTA As PROSPECTO_RECURSOS_LISTADataTable
    
    Private tablePROSPECTOS_COSTO_TERCEROS_LISTA As PROSPECTOS_COSTO_TERCEROS_LISTADataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("PROSPECTO_RECURSOS_LISTA")) Is Nothing) Then
                MyBase.Tables.Add(New PROSPECTO_RECURSOS_LISTADataTable(ds.Tables("PROSPECTO_RECURSOS_LISTA")))
            End If
            If (Not (ds.Tables("PROSPECTOS_COSTO_TERCEROS_LISTA")) Is Nothing) Then
                MyBase.Tables.Add(New PROSPECTOS_COSTO_TERCEROS_LISTADataTable(ds.Tables("PROSPECTOS_COSTO_TERCEROS_LISTA")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property PROSPECTO_RECURSOS_LISTA() As PROSPECTO_RECURSOS_LISTADataTable
        Get
            Return Me.tablePROSPECTO_RECURSOS_LISTA
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property PROSPECTOS_COSTO_TERCEROS_LISTA() As PROSPECTOS_COSTO_TERCEROS_LISTADataTable
        Get
            Return Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsProspectos = CType(MyBase.Clone,dsProspectos)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet()
            ds.ReadXml(reader)
            If (Not (ds.Tables("PROSPECTO_RECURSOS_LISTA")) Is Nothing) Then
                MyBase.Tables.Add(New PROSPECTO_RECURSOS_LISTADataTable(ds.Tables("PROSPECTO_RECURSOS_LISTA")))
            End If
            If (Not (ds.Tables("PROSPECTOS_COSTO_TERCEROS_LISTA")) Is Nothing) Then
                MyBase.Tables.Add(New PROSPECTOS_COSTO_TERCEROS_LISTADataTable(ds.Tables("PROSPECTOS_COSTO_TERCEROS_LISTA")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablePROSPECTO_RECURSOS_LISTA = CType(MyBase.Tables("PROSPECTO_RECURSOS_LISTA"),PROSPECTO_RECURSOS_LISTADataTable)
        If (initTable = true) Then
            If (Not (Me.tablePROSPECTO_RECURSOS_LISTA) Is Nothing) Then
                Me.tablePROSPECTO_RECURSOS_LISTA.InitVars
            End If
        End If
        Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA = CType(MyBase.Tables("PROSPECTOS_COSTO_TERCEROS_LISTA"),PROSPECTOS_COSTO_TERCEROS_LISTADataTable)
        If (initTable = true) Then
            If (Not (Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA) Is Nothing) Then
                Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub InitClass()
        Me.DataSetName = "dsProspectos"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/dsProspectos.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablePROSPECTO_RECURSOS_LISTA = New PROSPECTO_RECURSOS_LISTADataTable()
        MyBase.Tables.Add(Me.tablePROSPECTO_RECURSOS_LISTA)
        Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA = New PROSPECTOS_COSTO_TERCEROS_LISTADataTable()
        MyBase.Tables.Add(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializePROSPECTO_RECURSOS_LISTA() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Function ShouldSerializePROSPECTOS_COSTO_TERCEROS_LISTA() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsProspectos = New dsProspectos()
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub PROSPECTO_RECURSOS_LISTARowChangeEventHandler(ByVal sender As Object, ByVal e As PROSPECTO_RECURSOS_LISTARowChangeEvent)
    
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Delegate Sub PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEventHandler(ByVal sender As Object, ByVal e As PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class PROSPECTO_RECURSOS_LISTADataTable
        Inherits Global.System.Data.TypedTableBase(Of PROSPECTO_RECURSOS_LISTARow)
        
        Private columnRECURSO As Global.System.Data.DataColumn
        
        Private columnCENTRO_COSTO As Global.System.Data.DataColumn
        
        Private columnCENTRO_COSTO_DESCRIPCION As Global.System.Data.DataColumn
        
        Private columnCODIGO As Global.System.Data.DataColumn
        
        Private columnCODIGO_DESCRIPCION As Global.System.Data.DataColumn
        
        Private columnCOSTO_HORA As Global.System.Data.DataColumn
        
        Private columnHORAS As Global.System.Data.DataColumn
        
        Private columnTOTAL_HORAS As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "PROSPECTO_RECURSOS_LISTA"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RECURSOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRECURSO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CENTRO_COSTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCENTRO_COSTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CENTRO_COSTO_DESCRIPCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCENTRO_COSTO_DESCRIPCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CODIGOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCODIGO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CODIGO_DESCRIPCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCODIGO_DESCRIPCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property COSTO_HORAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOSTO_HORA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property HORASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnHORAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TOTAL_HORASColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTOTAL_HORAS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As PROSPECTO_RECURSOS_LISTARow
            Get
                Return CType(Me.Rows(index),PROSPECTO_RECURSOS_LISTARow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTO_RECURSOS_LISTARowChanging As PROSPECTO_RECURSOS_LISTARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTO_RECURSOS_LISTARowChanged As PROSPECTO_RECURSOS_LISTARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTO_RECURSOS_LISTARowDeleting As PROSPECTO_RECURSOS_LISTARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTO_RECURSOS_LISTARowDeleted As PROSPECTO_RECURSOS_LISTARowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddPROSPECTO_RECURSOS_LISTARow(ByVal row As PROSPECTO_RECURSOS_LISTARow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddPROSPECTO_RECURSOS_LISTARow(ByVal RECURSO As String, ByVal CENTRO_COSTO As String, ByVal CENTRO_COSTO_DESCRIPCION As String, ByVal CODIGO As String, ByVal CODIGO_DESCRIPCION As String, ByVal COSTO_HORA As Decimal, ByVal HORAS As Decimal, ByVal TOTAL_HORAS As Decimal) As PROSPECTO_RECURSOS_LISTARow
            Dim rowPROSPECTO_RECURSOS_LISTARow As PROSPECTO_RECURSOS_LISTARow = CType(Me.NewRow,PROSPECTO_RECURSOS_LISTARow)
            Dim columnValuesArray() As Object = New Object() {RECURSO, CENTRO_COSTO, CENTRO_COSTO_DESCRIPCION, CODIGO, CODIGO_DESCRIPCION, COSTO_HORA, HORAS, TOTAL_HORAS}
            rowPROSPECTO_RECURSOS_LISTARow.ItemArray = columnValuesArray
            Me.Rows.Add(rowPROSPECTO_RECURSOS_LISTARow)
            Return rowPROSPECTO_RECURSOS_LISTARow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As PROSPECTO_RECURSOS_LISTADataTable = CType(MyBase.Clone,PROSPECTO_RECURSOS_LISTADataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New PROSPECTO_RECURSOS_LISTADataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnRECURSO = MyBase.Columns("RECURSO")
            Me.columnCENTRO_COSTO = MyBase.Columns("CENTRO_COSTO")
            Me.columnCENTRO_COSTO_DESCRIPCION = MyBase.Columns("CENTRO_COSTO_DESCRIPCION")
            Me.columnCODIGO = MyBase.Columns("CODIGO")
            Me.columnCODIGO_DESCRIPCION = MyBase.Columns("CODIGO_DESCRIPCION")
            Me.columnCOSTO_HORA = MyBase.Columns("COSTO_HORA")
            Me.columnHORAS = MyBase.Columns("HORAS")
            Me.columnTOTAL_HORAS = MyBase.Columns("TOTAL_HORAS")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnRECURSO = New Global.System.Data.DataColumn("RECURSO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRECURSO)
            Me.columnCENTRO_COSTO = New Global.System.Data.DataColumn("CENTRO_COSTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCENTRO_COSTO)
            Me.columnCENTRO_COSTO_DESCRIPCION = New Global.System.Data.DataColumn("CENTRO_COSTO_DESCRIPCION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCENTRO_COSTO_DESCRIPCION)
            Me.columnCODIGO = New Global.System.Data.DataColumn("CODIGO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCODIGO)
            Me.columnCODIGO_DESCRIPCION = New Global.System.Data.DataColumn("CODIGO_DESCRIPCION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCODIGO_DESCRIPCION)
            Me.columnCOSTO_HORA = New Global.System.Data.DataColumn("COSTO_HORA", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOSTO_HORA)
            Me.columnHORAS = New Global.System.Data.DataColumn("HORAS", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnHORAS)
            Me.columnTOTAL_HORAS = New Global.System.Data.DataColumn("TOTAL_HORAS", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTOTAL_HORAS)
            Me.columnRECURSO.AllowDBNull = false
            Me.columnRECURSO.MaxLength = 3
            Me.columnCENTRO_COSTO.AllowDBNull = false
            Me.columnCENTRO_COSTO.MaxLength = 10
            Me.columnCENTRO_COSTO_DESCRIPCION.AllowDBNull = false
            Me.columnCENTRO_COSTO_DESCRIPCION.MaxLength = 30
            Me.columnCODIGO.AllowDBNull = false
            Me.columnCODIGO.MaxLength = 10
            Me.columnCODIGO_DESCRIPCION.AllowDBNull = false
            Me.columnCODIGO_DESCRIPCION.MaxLength = 30
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewPROSPECTO_RECURSOS_LISTARow() As PROSPECTO_RECURSOS_LISTARow
            Return CType(Me.NewRow,PROSPECTO_RECURSOS_LISTARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New PROSPECTO_RECURSOS_LISTARow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(PROSPECTO_RECURSOS_LISTARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.PROSPECTO_RECURSOS_LISTARowChangedEvent) Is Nothing) Then
                RaiseEvent PROSPECTO_RECURSOS_LISTARowChanged(Me, New PROSPECTO_RECURSOS_LISTARowChangeEvent(CType(e.Row,PROSPECTO_RECURSOS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.PROSPECTO_RECURSOS_LISTARowChangingEvent) Is Nothing) Then
                RaiseEvent PROSPECTO_RECURSOS_LISTARowChanging(Me, New PROSPECTO_RECURSOS_LISTARowChangeEvent(CType(e.Row,PROSPECTO_RECURSOS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.PROSPECTO_RECURSOS_LISTARowDeletedEvent) Is Nothing) Then
                RaiseEvent PROSPECTO_RECURSOS_LISTARowDeleted(Me, New PROSPECTO_RECURSOS_LISTARowChangeEvent(CType(e.Row,PROSPECTO_RECURSOS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.PROSPECTO_RECURSOS_LISTARowDeletingEvent) Is Nothing) Then
                RaiseEvent PROSPECTO_RECURSOS_LISTARowDeleting(Me, New PROSPECTO_RECURSOS_LISTARowChangeEvent(CType(e.Row,PROSPECTO_RECURSOS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemovePROSPECTO_RECURSOS_LISTARow(ByVal row As PROSPECTO_RECURSOS_LISTARow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As dsProspectos = New dsProspectos()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "PROSPECTO_RECURSOS_LISTADataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class PROSPECTOS_COSTO_TERCEROS_LISTADataTable
        Inherits Global.System.Data.TypedTableBase(Of PROSPECTOS_COSTO_TERCEROS_LISTARow)
        
        Private columnEMPRESA As Global.System.Data.DataColumn
        
        Private columnPROSPECTO As Global.System.Data.DataColumn
        
        Private columnCOSTO As Global.System.Data.DataColumn
        
        Private columnTIPO_PROVEEDOR As Global.System.Data.DataColumn
        
        Private columnTIPO_PROVEEDOR_DESCRIPCION As Global.System.Data.DataColumn
        
        Private columnCUENTA_COMERCIAL As Global.System.Data.DataColumn
        
        Private columnRAZON_SOCIAL As Global.System.Data.DataColumn
        
        Private columnMONEDA As Global.System.Data.DataColumn
        
        Private columnVALOR_VENTA As Global.System.Data.DataColumn
        
        Private columnTIPO_IMPUESTO As Global.System.Data.DataColumn
        
        Private columnVALOR_VENTA_MN As Global.System.Data.DataColumn
        
        Private columnVALOR_VENTA_ME As Global.System.Data.DataColumn
        
        Private columnVALOR_VENTA_FINAL_MN As Global.System.Data.DataColumn
        
        Private columnVALOR_VENTA_FINAL_ME As Global.System.Data.DataColumn
        
        Private columnCOSTO_TOTAL_MN As Global.System.Data.DataColumn
        
        Private columnCOTIZACION_PROVEEDOR As Global.System.Data.DataColumn
        
        Private columnINDICA_SELECCION As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "PROSPECTOS_COSTO_TERCEROS_LISTA"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property EMPRESAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnEMPRESA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property PROSPECTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPROSPECTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property COSTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOSTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_PROVEEDORColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_PROVEEDOR
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_PROVEEDOR_DESCRIPCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_PROVEEDOR_DESCRIPCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property CUENTA_COMERCIALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCUENTA_COMERCIAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property RAZON_SOCIALColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRAZON_SOCIAL
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property MONEDAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMONEDA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VALOR_VENTAColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVALOR_VENTA
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property TIPO_IMPUESTOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnTIPO_IMPUESTO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VALOR_VENTA_MNColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVALOR_VENTA_MN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VALOR_VENTA_MEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVALOR_VENTA_ME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VALOR_VENTA_FINAL_MNColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVALOR_VENTA_FINAL_MN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property VALOR_VENTA_FINAL_MEColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnVALOR_VENTA_FINAL_ME
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property COSTO_TOTAL_MNColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOSTO_TOTAL_MN
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property COTIZACION_PROVEEDORColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCOTIZACION_PROVEEDOR
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property INDICA_SELECCIONColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnINDICA_SELECCION
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0"),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As PROSPECTOS_COSTO_TERCEROS_LISTARow
            Get
                Return CType(Me.Rows(index),PROSPECTOS_COSTO_TERCEROS_LISTARow)
            End Get
        End Property
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTOS_COSTO_TERCEROS_LISTARowChanging As PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTOS_COSTO_TERCEROS_LISTARowChanged As PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTOS_COSTO_TERCEROS_LISTARowDeleting As PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEventHandler
        
        <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Event PROSPECTOS_COSTO_TERCEROS_LISTARowDeleted As PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Sub AddPROSPECTOS_COSTO_TERCEROS_LISTARow(ByVal row As PROSPECTOS_COSTO_TERCEROS_LISTARow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overloads Function AddPROSPECTOS_COSTO_TERCEROS_LISTARow( _
                    ByVal EMPRESA As String,  _
                    ByVal PROSPECTO As String,  _
                    ByVal COSTO As String,  _
                    ByVal TIPO_PROVEEDOR As String,  _
                    ByVal TIPO_PROVEEDOR_DESCRIPCION As String,  _
                    ByVal CUENTA_COMERCIAL As String,  _
                    ByVal RAZON_SOCIAL As String,  _
                    ByVal MONEDA As String,  _
                    ByVal VALOR_VENTA As Decimal,  _
                    ByVal TIPO_IMPUESTO As String,  _
                    ByVal VALOR_VENTA_MN As Decimal,  _
                    ByVal VALOR_VENTA_ME As Decimal,  _
                    ByVal VALOR_VENTA_FINAL_MN As Decimal,  _
                    ByVal VALOR_VENTA_FINAL_ME As Decimal,  _
                    ByVal COSTO_TOTAL_MN As Decimal,  _
                    ByVal COTIZACION_PROVEEDOR As String,  _
                    ByVal INDICA_SELECCION As Integer) As PROSPECTOS_COSTO_TERCEROS_LISTARow
            Dim rowPROSPECTOS_COSTO_TERCEROS_LISTARow As PROSPECTOS_COSTO_TERCEROS_LISTARow = CType(Me.NewRow,PROSPECTOS_COSTO_TERCEROS_LISTARow)
            Dim columnValuesArray() As Object = New Object() {EMPRESA, PROSPECTO, COSTO, TIPO_PROVEEDOR, TIPO_PROVEEDOR_DESCRIPCION, CUENTA_COMERCIAL, RAZON_SOCIAL, MONEDA, VALOR_VENTA, TIPO_IMPUESTO, VALOR_VENTA_MN, VALOR_VENTA_ME, VALOR_VENTA_FINAL_MN, VALOR_VENTA_FINAL_ME, COSTO_TOTAL_MN, COTIZACION_PROVEEDOR, INDICA_SELECCION}
            rowPROSPECTOS_COSTO_TERCEROS_LISTARow.ItemArray = columnValuesArray
            Me.Rows.Add(rowPROSPECTOS_COSTO_TERCEROS_LISTARow)
            Return rowPROSPECTOS_COSTO_TERCEROS_LISTARow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function FindByEMPRESAPROSPECTOCOSTO(ByVal EMPRESA As String, ByVal PROSPECTO As String, ByVal COSTO As String) As PROSPECTOS_COSTO_TERCEROS_LISTARow
            Return CType(Me.Rows.Find(New Object() {EMPRESA, PROSPECTO, COSTO}),PROSPECTOS_COSTO_TERCEROS_LISTARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As PROSPECTOS_COSTO_TERCEROS_LISTADataTable = CType(MyBase.Clone,PROSPECTOS_COSTO_TERCEROS_LISTADataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New PROSPECTOS_COSTO_TERCEROS_LISTADataTable()
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub InitVars()
            Me.columnEMPRESA = MyBase.Columns("EMPRESA")
            Me.columnPROSPECTO = MyBase.Columns("PROSPECTO")
            Me.columnCOSTO = MyBase.Columns("COSTO")
            Me.columnTIPO_PROVEEDOR = MyBase.Columns("TIPO_PROVEEDOR")
            Me.columnTIPO_PROVEEDOR_DESCRIPCION = MyBase.Columns("TIPO_PROVEEDOR_DESCRIPCION")
            Me.columnCUENTA_COMERCIAL = MyBase.Columns("CUENTA_COMERCIAL")
            Me.columnRAZON_SOCIAL = MyBase.Columns("RAZON_SOCIAL")
            Me.columnMONEDA = MyBase.Columns("MONEDA")
            Me.columnVALOR_VENTA = MyBase.Columns("VALOR_VENTA")
            Me.columnTIPO_IMPUESTO = MyBase.Columns("TIPO_IMPUESTO")
            Me.columnVALOR_VENTA_MN = MyBase.Columns("VALOR_VENTA_MN")
            Me.columnVALOR_VENTA_ME = MyBase.Columns("VALOR_VENTA_ME")
            Me.columnVALOR_VENTA_FINAL_MN = MyBase.Columns("VALOR_VENTA_FINAL_MN")
            Me.columnVALOR_VENTA_FINAL_ME = MyBase.Columns("VALOR_VENTA_FINAL_ME")
            Me.columnCOSTO_TOTAL_MN = MyBase.Columns("COSTO_TOTAL_MN")
            Me.columnCOTIZACION_PROVEEDOR = MyBase.Columns("COTIZACION_PROVEEDOR")
            Me.columnINDICA_SELECCION = MyBase.Columns("INDICA_SELECCION")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Private Sub InitClass()
            Me.columnEMPRESA = New Global.System.Data.DataColumn("EMPRESA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnEMPRESA)
            Me.columnPROSPECTO = New Global.System.Data.DataColumn("PROSPECTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPROSPECTO)
            Me.columnCOSTO = New Global.System.Data.DataColumn("COSTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOSTO)
            Me.columnTIPO_PROVEEDOR = New Global.System.Data.DataColumn("TIPO_PROVEEDOR", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_PROVEEDOR)
            Me.columnTIPO_PROVEEDOR_DESCRIPCION = New Global.System.Data.DataColumn("TIPO_PROVEEDOR_DESCRIPCION", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_PROVEEDOR_DESCRIPCION)
            Me.columnCUENTA_COMERCIAL = New Global.System.Data.DataColumn("CUENTA_COMERCIAL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCUENTA_COMERCIAL)
            Me.columnRAZON_SOCIAL = New Global.System.Data.DataColumn("RAZON_SOCIAL", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRAZON_SOCIAL)
            Me.columnMONEDA = New Global.System.Data.DataColumn("MONEDA", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMONEDA)
            Me.columnVALOR_VENTA = New Global.System.Data.DataColumn("VALOR_VENTA", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVALOR_VENTA)
            Me.columnTIPO_IMPUESTO = New Global.System.Data.DataColumn("TIPO_IMPUESTO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnTIPO_IMPUESTO)
            Me.columnVALOR_VENTA_MN = New Global.System.Data.DataColumn("VALOR_VENTA_MN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVALOR_VENTA_MN)
            Me.columnVALOR_VENTA_ME = New Global.System.Data.DataColumn("VALOR_VENTA_ME", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVALOR_VENTA_ME)
            Me.columnVALOR_VENTA_FINAL_MN = New Global.System.Data.DataColumn("VALOR_VENTA_FINAL_MN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVALOR_VENTA_FINAL_MN)
            Me.columnVALOR_VENTA_FINAL_ME = New Global.System.Data.DataColumn("VALOR_VENTA_FINAL_ME", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnVALOR_VENTA_FINAL_ME)
            Me.columnCOSTO_TOTAL_MN = New Global.System.Data.DataColumn("COSTO_TOTAL_MN", GetType(Decimal), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOSTO_TOTAL_MN)
            Me.columnCOTIZACION_PROVEEDOR = New Global.System.Data.DataColumn("COTIZACION_PROVEEDOR", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCOTIZACION_PROVEEDOR)
            Me.columnINDICA_SELECCION = New Global.System.Data.DataColumn("INDICA_SELECCION", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnINDICA_SELECCION)
            Me.Constraints.Add(New Global.System.Data.UniqueConstraint("Constraint1", New Global.System.Data.DataColumn() {Me.columnEMPRESA, Me.columnPROSPECTO, Me.columnCOSTO}, true))
            Me.columnEMPRESA.AllowDBNull = false
            Me.columnEMPRESA.MaxLength = 3
            Me.columnPROSPECTO.AllowDBNull = false
            Me.columnPROSPECTO.MaxLength = 12
            Me.columnCOSTO.AllowDBNull = false
            Me.columnCOSTO.MaxLength = 3
            Me.columnTIPO_PROVEEDOR.AllowDBNull = false
            Me.columnTIPO_PROVEEDOR.MaxLength = 4
            Me.columnTIPO_PROVEEDOR_DESCRIPCION.ReadOnly = true
            Me.columnTIPO_PROVEEDOR_DESCRIPCION.MaxLength = 27
            Me.columnCUENTA_COMERCIAL.AllowDBNull = false
            Me.columnCUENTA_COMERCIAL.MaxLength = 18
            Me.columnRAZON_SOCIAL.AllowDBNull = false
            Me.columnRAZON_SOCIAL.MaxLength = 50
            Me.columnMONEDA.ReadOnly = true
            Me.columnMONEDA.MaxLength = 3
            Me.columnTIPO_IMPUESTO.AllowDBNull = false
            Me.columnTIPO_IMPUESTO.MaxLength = 2
            Me.columnVALOR_VENTA_FINAL_MN.ReadOnly = true
            Me.columnVALOR_VENTA_FINAL_ME.ReadOnly = true
            Me.columnCOSTO_TOTAL_MN.ReadOnly = true
            Me.columnCOTIZACION_PROVEEDOR.AllowDBNull = false
            Me.columnCOTIZACION_PROVEEDOR.MaxLength = 150
            Me.columnINDICA_SELECCION.ReadOnly = true
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function NewPROSPECTOS_COSTO_TERCEROS_LISTARow() As PROSPECTOS_COSTO_TERCEROS_LISTARow
            Return CType(Me.NewRow,PROSPECTOS_COSTO_TERCEROS_LISTARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New PROSPECTOS_COSTO_TERCEROS_LISTARow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(PROSPECTOS_COSTO_TERCEROS_LISTARow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.PROSPECTOS_COSTO_TERCEROS_LISTARowChangedEvent) Is Nothing) Then
                RaiseEvent PROSPECTOS_COSTO_TERCEROS_LISTARowChanged(Me, New PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEvent(CType(e.Row,PROSPECTOS_COSTO_TERCEROS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.PROSPECTOS_COSTO_TERCEROS_LISTARowChangingEvent) Is Nothing) Then
                RaiseEvent PROSPECTOS_COSTO_TERCEROS_LISTARowChanging(Me, New PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEvent(CType(e.Row,PROSPECTOS_COSTO_TERCEROS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.PROSPECTOS_COSTO_TERCEROS_LISTARowDeletedEvent) Is Nothing) Then
                RaiseEvent PROSPECTOS_COSTO_TERCEROS_LISTARowDeleted(Me, New PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEvent(CType(e.Row,PROSPECTOS_COSTO_TERCEROS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.PROSPECTOS_COSTO_TERCEROS_LISTARowDeletingEvent) Is Nothing) Then
                RaiseEvent PROSPECTOS_COSTO_TERCEROS_LISTARowDeleting(Me, New PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEvent(CType(e.Row,PROSPECTOS_COSTO_TERCEROS_LISTARow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub RemovePROSPECTOS_COSTO_TERCEROS_LISTARow(ByVal row As PROSPECTOS_COSTO_TERCEROS_LISTARow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType()
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence()
            Dim ds As dsProspectos = New dsProspectos()
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny()
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute()
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "PROSPECTOS_COSTO_TERCEROS_LISTADataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream()
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class PROSPECTO_RECURSOS_LISTARow
        Inherits Global.System.Data.DataRow
        
        Private tablePROSPECTO_RECURSOS_LISTA As PROSPECTO_RECURSOS_LISTADataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablePROSPECTO_RECURSOS_LISTA = CType(Me.Table,PROSPECTO_RECURSOS_LISTADataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RECURSO() As String
            Get
                Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.RECURSOColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.RECURSOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CENTRO_COSTO() As String
            Get
                Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.CENTRO_COSTOColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.CENTRO_COSTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CENTRO_COSTO_DESCRIPCION() As String
            Get
                Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.CENTRO_COSTO_DESCRIPCIONColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.CENTRO_COSTO_DESCRIPCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CODIGO() As String
            Get
                Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.CODIGOColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.CODIGOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CODIGO_DESCRIPCION() As String
            Get
                Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.CODIGO_DESCRIPCIONColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.CODIGO_DESCRIPCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property COSTO_HORA() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.COSTO_HORAColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'COSTO_HORA' de la tabla 'PROSPECTO_RECURSOS_LISTA' es DBN"& _ 
                            "ull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.COSTO_HORAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property HORAS() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.HORASColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'HORAS' de la tabla 'PROSPECTO_RECURSOS_LISTA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.HORASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TOTAL_HORAS() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTO_RECURSOS_LISTA.TOTAL_HORASColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'TOTAL_HORAS' de la tabla 'PROSPECTO_RECURSOS_LISTA' es DB"& _ 
                            "Null.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTO_RECURSOS_LISTA.TOTAL_HORASColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCOSTO_HORANull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTO_RECURSOS_LISTA.COSTO_HORAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCOSTO_HORANull()
            Me(Me.tablePROSPECTO_RECURSOS_LISTA.COSTO_HORAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsHORASNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTO_RECURSOS_LISTA.HORASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetHORASNull()
            Me(Me.tablePROSPECTO_RECURSOS_LISTA.HORASColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTOTAL_HORASNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTO_RECURSOS_LISTA.TOTAL_HORASColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTOTAL_HORASNull()
            Me(Me.tablePROSPECTO_RECURSOS_LISTA.TOTAL_HORASColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    Partial Public Class PROSPECTOS_COSTO_TERCEROS_LISTARow
        Inherits Global.System.Data.DataRow
        
        Private tablePROSPECTOS_COSTO_TERCEROS_LISTA As PROSPECTOS_COSTO_TERCEROS_LISTADataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA = CType(Me.Table,PROSPECTOS_COSTO_TERCEROS_LISTADataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property EMPRESA() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.EMPRESAColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.EMPRESAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property PROSPECTO() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.PROSPECTOColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.PROSPECTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property COSTO() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COSTOColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COSTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_PROVEEDOR() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_PROVEEDORColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_PROVEEDORColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_PROVEEDOR_DESCRIPCION() As String
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_PROVEEDOR_DESCRIPCIONColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'TIPO_PROVEEDOR_DESCRIPCION' de la tabla 'PROSPECTOS_COSTO"& _ 
                            "_TERCEROS_LISTA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_PROVEEDOR_DESCRIPCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property CUENTA_COMERCIAL() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.CUENTA_COMERCIALColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.CUENTA_COMERCIALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property RAZON_SOCIAL() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.RAZON_SOCIALColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.RAZON_SOCIALColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property MONEDA() As String
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.MONEDAColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'MONEDA' de la tabla 'PROSPECTOS_COSTO_TERCEROS_LISTA' es "& _ 
                            "DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.MONEDAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VALOR_VENTA() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTAColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'VALOR_VENTA' de la tabla 'PROSPECTOS_COSTO_TERCEROS_LISTA"& _ 
                            "' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTAColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property TIPO_IMPUESTO() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_IMPUESTOColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_IMPUESTOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VALOR_VENTA_MN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MNColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'VALOR_VENTA_MN' de la tabla 'PROSPECTOS_COSTO_TERCEROS_LI"& _ 
                            "STA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MNColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VALOR_VENTA_ME() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MEColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'VALOR_VENTA_ME' de la tabla 'PROSPECTOS_COSTO_TERCEROS_LI"& _ 
                            "STA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VALOR_VENTA_FINAL_MN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MNColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'VALOR_VENTA_FINAL_MN' de la tabla 'PROSPECTOS_COSTO_TERCE"& _ 
                            "ROS_LISTA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MNColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property VALOR_VENTA_FINAL_ME() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MEColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'VALOR_VENTA_FINAL_ME' de la tabla 'PROSPECTOS_COSTO_TERCE"& _ 
                            "ROS_LISTA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MEColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property COSTO_TOTAL_MN() As Decimal
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COSTO_TOTAL_MNColumn),Decimal)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'COSTO_TOTAL_MN' de la tabla 'PROSPECTOS_COSTO_TERCEROS_LI"& _ 
                            "STA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COSTO_TOTAL_MNColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property COTIZACION_PROVEEDOR() As String
            Get
                Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COTIZACION_PROVEEDORColumn),String)
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COTIZACION_PROVEEDORColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Property INDICA_SELECCION() As Integer
            Get
                Try 
                    Return CType(Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.INDICA_SELECCIONColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("El valor de la columna 'INDICA_SELECCION' de la tabla 'PROSPECTOS_COSTO_TERCEROS_"& _ 
                            "LISTA' es DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.INDICA_SELECCIONColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsTIPO_PROVEEDOR_DESCRIPCIONNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_PROVEEDOR_DESCRIPCIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetTIPO_PROVEEDOR_DESCRIPCIONNull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.TIPO_PROVEEDOR_DESCRIPCIONColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsMONEDANull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.MONEDAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetMONEDANull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.MONEDAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVALOR_VENTANull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTAColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVALOR_VENTANull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTAColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVALOR_VENTA_MNNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MNColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVALOR_VENTA_MNNull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MNColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVALOR_VENTA_MENull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVALOR_VENTA_MENull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_MEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVALOR_VENTA_FINAL_MNNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MNColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVALOR_VENTA_FINAL_MNNull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MNColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsVALOR_VENTA_FINAL_MENull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MEColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetVALOR_VENTA_FINAL_MENull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.VALOR_VENTA_FINAL_MEColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsCOSTO_TOTAL_MNNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COSTO_TOTAL_MNColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetCOSTO_TOTAL_MNNull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.COSTO_TOTAL_MNColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Function IsINDICA_SELECCIONNull() As Boolean
            Return Me.IsNull(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.INDICA_SELECCIONColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub SetINDICA_SELECCIONNull()
            Me(Me.tablePROSPECTOS_COSTO_TERCEROS_LISTA.INDICA_SELECCIONColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class PROSPECTO_RECURSOS_LISTARowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As PROSPECTO_RECURSOS_LISTARow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As PROSPECTO_RECURSOS_LISTARow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As PROSPECTO_RECURSOS_LISTARow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
    Public Class PROSPECTOS_COSTO_TERCEROS_LISTARowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As PROSPECTOS_COSTO_TERCEROS_LISTARow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public Sub New(ByVal row As PROSPECTOS_COSTO_TERCEROS_LISTARow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Row() As PROSPECTOS_COSTO_TERCEROS_LISTARow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "4.0.0.0")>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
